// ==========================================
// Templates - תבניות מוכנות למסגרות מגנט
// ==========================================

import { CanvasElement, TextElement, ShapeElement, ImageElement, PlaceholderElement } from './types';

export interface Template {
  id: string;
  name: string;
  nameHe: string;
  category: TemplateCategory;
  description: string;
  thumbnail?: string;
  canvasWidth: number;
  canvasHeight: number;
  elements: CanvasElement[];
}

export type TemplateCategory = 
  | 'wedding'      // חתונות
  | 'birthday'     // ימי הולדת
  | 'baby'         // תינוקות
  | 'family'       // משפחה
  | 'event'        // אירועים
  | 'business'     // עסקי
  | 'blank';       // ריק

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; name: string; icon: string }[] = [
  { id: 'blank', name: 'ריק', icon: '⬜' },
  { id: 'wedding', name: 'חתונה', icon: '💒' },
  { id: 'birthday', name: 'יום הולדת', icon: '🎂' },
  { id: 'baby', name: 'תינוק', icon: '👶' },
  { id: 'family', name: 'משפחה', icon: '👨‍👩‍👧‍👦' },
  { id: 'event', name: 'אירוע', icon: '🎉' },
  { id: 'business', name: 'עסקי', icon: '💼' },
];

// Standard magnet frame sizes (in mm, converted to pixels at 300 DPI)
export const FRAME_SIZES = {
  small: { width: 354, height: 472, label: '3×4 אינץ׳' },      // 3x4 inch
  medium: { width: 472, height: 590, label: '4×5 אינץ׳' },     // 4x5 inch
  large: { width: 590, height: 708, label: '5×6 אינץ׳' },      // 5x6 inch
  square: { width: 472, height: 472, label: '4×4 אינץ׳' },     // 4x4 inch
  custom: { width: 600, height: 800, label: 'מותאם אישית' },
};

// Helper to generate unique IDs
const generateId = () => `el_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// Default element factories
const createTextElement = (overrides: Partial<TextElement>): TextElement => ({
  id: generateId(),
  type: 'text',
  name: 'טקסט',
  x: 100,
  y: 100,
  width: 200,
  height: 50,
  rotation: 0,
  scaleX: 1,
  scaleY: 1,
  opacity: 1,
  zIndex: 0,
  isLocked: false,
  isVisible: true,
  text: 'טקסט',
  fontFamily: 'Assistant',
  fontSize: 24,
  fontStyle: 'normal',
  fontWeight: 400,
  fill: '#333333',
  textAlign: 'center',
  direction: 'rtl',
  lineHeight: 1.2,
  letterSpacing: 0,
  ...overrides,
});

const createShapeElement = (overrides: Partial<ShapeElement>): ShapeElement => ({
  id: generateId(),
  type: 'shape',
  name: 'צורה',
  x: 100,
  y: 100,
  width: 100,
  height: 100,
  rotation: 0,
  scaleX: 1,
  scaleY: 1,
  opacity: 1,
  zIndex: 0,
  isLocked: false,
  isVisible: true,
  shapeType: 'rectangle',
  fill: '#6366f1',
  stroke: '#4f46e5',
  strokeWidth: 0,
  strokeStyle: 'solid',
  ...overrides,
});

const createImagePlaceholder = (overrides: Partial<ImageElement>): ImageElement => ({
  id: generateId(),
  type: 'image',
  name: 'מקום לתמונה',
  x: 100,
  y: 100,
  width: 200,
  height: 200,
  rotation: 0,
  scaleX: 1,
  scaleY: 1,
  opacity: 1,
  zIndex: 0,
  isLocked: false,
  isVisible: true,
  src: '', // Empty = placeholder
  originalWidth: 200,
  originalHeight: 200,
  objectFit: 'cover',
  ...overrides,
});

// Create a Placeholder element for image insertion
const createPlaceholder = (overrides: Partial<PlaceholderElement>): PlaceholderElement => ({
  id: generateId(),
  type: 'placeholder',
  name: 'אזור תמונה',
  x: 100,
  y: 100,
  width: 200,
  height: 200,
  rotation: 0,
  scaleX: 1,
  scaleY: 1,
  opacity: 1,
  zIndex: 0,
  isLocked: false,
  isVisible: true,
  shape: 'rectangle',
  fill: '#f3f4f6',
  stroke: '#9ca3af',
  strokeWidth: 2,
  cornerRadius: 8,
  label: 'גרור תמונה לכאן',
  ...overrides,
});

// ==========================================
// TEMPLATES
// ==========================================

export const TEMPLATES: Template[] = [
  // ========== BLANK ==========
  {
    id: 'blank-small',
    name: 'Blank Small',
    nameHe: 'ריק קטן',
    category: 'blank',
    description: 'תבנית ריקה בגודל 3×4 אינץ׳',
    canvasWidth: FRAME_SIZES.small.width,
    canvasHeight: FRAME_SIZES.small.height,
    elements: [],
  },
  {
    id: 'blank-medium',
    name: 'Blank Medium',
    nameHe: 'ריק בינוני',
    category: 'blank',
    description: 'תבנית ריקה בגודל 4×5 אינץ׳',
    canvasWidth: FRAME_SIZES.medium.width,
    canvasHeight: FRAME_SIZES.medium.height,
    elements: [],
  },
  {
    id: 'blank-square',
    name: 'Blank Square',
    nameHe: 'ריק מרובע',
    category: 'blank',
    description: 'תבנית ריקה בגודל 4×4 אינץ׳',
    canvasWidth: FRAME_SIZES.square.width,
    canvasHeight: FRAME_SIZES.square.height,
    elements: [],
  },

  // ========== NEW: Template with Placeholders ==========
  {
    id: 'wedding-with-placeholders',
    name: 'Wedding Placeholders',
    nameHe: 'חתונה עם אזורי תמונה',
    category: 'wedding',
    description: 'תבנית חתונה עם אזורים חכמים לגרירת תמונות',
    canvasWidth: 600,
    canvasHeight: 800,
    elements: [
      // Background
      createShapeElement({
        id: 'bg-placeholder-1',
        name: 'רקע',
        x: 0,
        y: 0,
        width: 600,
        height: 800,
        fill: '#fdf6f0',
        zIndex: 0,
        isLocked: true,
      }),
      // Main photo placeholder
      createPlaceholder({
        id: 'main-photo-placeholder',
        name: 'תמונה ראשית',
        x: 50,
        y: 100,
        width: 500,
        height: 350,
        shape: 'rounded',
        cornerRadius: 16,
        fill: '#f8f4f0',
        stroke: '#d4af37',
        strokeWidth: 3,
        label: 'תמונת הזוג',
        zIndex: 1,
      }),
      // Small photo placeholder 1
      createPlaceholder({
        id: 'small-photo-1',
        name: 'תמונה קטנה 1',
        x: 50,
        y: 480,
        width: 150,
        height: 150,
        shape: 'circle',
        fill: '#f8f4f0',
        stroke: '#d4af37',
        strokeWidth: 2,
        label: 'תמונה 1',
        zIndex: 2,
      }),
      // Small photo placeholder 2
      createPlaceholder({
        id: 'small-photo-2',
        name: 'תמונה קטנה 2',
        x: 225,
        y: 480,
        width: 150,
        height: 150,
        shape: 'circle',
        fill: '#f8f4f0',
        stroke: '#d4af37',
        strokeWidth: 2,
        label: 'תמונה 2',
        zIndex: 3,
      }),
      // Small photo placeholder 3
      createPlaceholder({
        id: 'small-photo-3',
        name: 'תמונה קטנה 3',
        x: 400,
        y: 480,
        width: 150,
        height: 150,
        shape: 'circle',
        fill: '#f8f4f0',
        stroke: '#d4af37',
        strokeWidth: 2,
        label: 'תמונה 3',
        zIndex: 4,
      }),
      // Names text
      createTextElement({
        id: 'names-placeholder',
        name: 'שמות',
        x: 50,
        y: 660,
        width: 500,
        height: 50,
        text: 'שרה ♥ דוד',
        fontFamily: 'David Libre',
        fontSize: 36,
        fill: '#333333',
        textAlign: 'center',
        zIndex: 5,
      }),
      // Date text
      createTextElement({
        id: 'date-placeholder',
        name: 'תאריך',
        x: 50,
        y: 720,
        width: 500,
        height: 30,
        text: 'כ״ו באלול תשפ״ד | 15.09.2024',
        fontFamily: 'Assistant',
        fontSize: 20,
        fill: '#666666',
        textAlign: 'center',
        zIndex: 6,
      }),
    ],
  },

  // ========== WEDDING ==========
  {
    id: 'wedding-elegant',
    name: 'Elegant Wedding',
    nameHe: 'חתונה אלגנטית',
    category: 'wedding',
    description: 'תבנית אלגנטית לחתונות עם מסגרת זהובה',
    canvasWidth: FRAME_SIZES.medium.width,
    canvasHeight: FRAME_SIZES.medium.height,
    elements: [
      // Background
      createShapeElement({
        id: 'bg-1',
        name: 'רקע',
        x: 0,
        y: 0,
        width: FRAME_SIZES.medium.width,
        height: FRAME_SIZES.medium.height,
        fill: '#faf7f2',
        zIndex: 0,
        isLocked: true,
      }),
      // Golden border
      createShapeElement({
        id: 'border-1',
        name: 'מסגרת',
        x: 15,
        y: 15,
        width: FRAME_SIZES.medium.width - 30,
        height: FRAME_SIZES.medium.height - 30,
        fill: 'transparent',
        stroke: '#d4af37',
        strokeWidth: 2,
        zIndex: 1,
      }),
      // Image placeholder
      createImagePlaceholder({
        id: 'photo-1',
        name: 'תמונת הזוג',
        x: 50,
        y: 80,
        width: FRAME_SIZES.medium.width - 100,
        height: 300,
        zIndex: 2,
      }),
      // Names
      createTextElement({
        id: 'names-1',
        name: 'שמות',
        x: 50,
        y: 400,
        width: FRAME_SIZES.medium.width - 100,
        height: 50,
        text: 'שרה & דוד',
        fontFamily: 'David Libre',
        fontSize: 32,
        fill: '#333333',
        textAlign: 'center',
        zIndex: 3,
      }),
      // Date
      createTextElement({
        id: 'date-1',
        name: 'תאריך',
        x: 50,
        y: 460,
        width: FRAME_SIZES.medium.width - 100,
        height: 30,
        text: '15.06.2024',
        fontFamily: 'Assistant',
        fontSize: 18,
        fill: '#666666',
        textAlign: 'center',
        zIndex: 4,
      }),
      // Heart decoration
      createTextElement({
        id: 'heart-1',
        name: 'לב',
        x: (FRAME_SIZES.medium.width - 40) / 2,
        y: 510,
        width: 40,
        height: 40,
        text: '❤️',
        fontSize: 28,
        textAlign: 'center',
        zIndex: 5,
      }),
    ],
  },
  {
    id: 'wedding-rustic',
    name: 'Rustic Wedding',
    nameHe: 'חתונה כפרית',
    category: 'wedding',
    description: 'תבנית בסגנון כפרי עם פרחים',
    canvasWidth: FRAME_SIZES.medium.width,
    canvasHeight: FRAME_SIZES.medium.height,
    elements: [
      createShapeElement({
        id: 'bg-2',
        name: 'רקע',
        x: 0,
        y: 0,
        width: FRAME_SIZES.medium.width,
        height: FRAME_SIZES.medium.height,
        fill: '#f5ebe0',
        zIndex: 0,
        isLocked: true,
      }),
      createImagePlaceholder({
        id: 'photo-2',
        name: 'תמונת הזוג',
        x: 40,
        y: 60,
        width: FRAME_SIZES.medium.width - 80,
        height: 320,
        borderRadius: 10,
        zIndex: 2,
      }),
      createTextElement({
        id: 'title-2',
        name: 'כותרת',
        x: 40,
        y: 400,
        width: FRAME_SIZES.medium.width - 80,
        height: 40,
        text: 'יחד לנצח',
        fontFamily: 'Secular One',
        fontSize: 28,
        fill: '#5c4033',
        textAlign: 'center',
        zIndex: 3,
      }),
      createTextElement({
        id: 'names-2',
        name: 'שמות',
        x: 40,
        y: 450,
        width: FRAME_SIZES.medium.width - 80,
        height: 35,
        text: 'מיכל & יוסי',
        fontFamily: 'Assistant',
        fontSize: 22,
        fill: '#8b7355',
        textAlign: 'center',
        zIndex: 4,
      }),
      createTextElement({
        id: 'date-2',
        name: 'תאריך',
        x: 40,
        y: 500,
        width: FRAME_SIZES.medium.width - 80,
        height: 30,
        text: '20 באוגוסט, 2024',
        fontFamily: 'Assistant',
        fontSize: 16,
        fill: '#999999',
        textAlign: 'center',
        zIndex: 5,
      }),
    ],
  },

  // ========== BIRTHDAY ==========
  {
    id: 'birthday-fun',
    name: 'Fun Birthday',
    nameHe: 'יום הולדת שמח',
    category: 'birthday',
    description: 'תבנית צבעונית ושמחה ליום הולדת',
    canvasWidth: FRAME_SIZES.medium.width,
    canvasHeight: FRAME_SIZES.medium.height,
    elements: [
      createShapeElement({
        id: 'bg-3',
        name: 'רקע',
        x: 0,
        y: 0,
        width: FRAME_SIZES.medium.width,
        height: FRAME_SIZES.medium.height,
        fill: '#fff0f5',
        zIndex: 0,
        isLocked: true,
      }),
      createTextElement({
        id: 'balloon-1',
        name: 'בלון 1',
        x: 30,
        y: 20,
        width: 50,
        height: 60,
        text: '🎈',
        fontSize: 40,
        zIndex: 1,
      }),
      createTextElement({
        id: 'balloon-2',
        name: 'בלון 2',
        x: FRAME_SIZES.medium.width - 80,
        y: 30,
        width: 50,
        height: 60,
        text: '🎈',
        fontSize: 40,
        zIndex: 1,
      }),
      createImagePlaceholder({
        id: 'photo-3',
        name: 'תמונת חוגג',
        x: 50,
        y: 100,
        width: FRAME_SIZES.medium.width - 100,
        height: 280,
        borderRadius: 15,
        zIndex: 2,
      }),
      createTextElement({
        id: 'title-3',
        name: 'כותרת',
        x: 30,
        y: 400,
        width: FRAME_SIZES.medium.width - 60,
        height: 50,
        text: 'יום הולדת שמח!',
        fontFamily: 'Secular One',
        fontSize: 30,
        fill: '#ff69b4',
        textAlign: 'center',
        zIndex: 3,
      }),
      createTextElement({
        id: 'name-3',
        name: 'שם',
        x: 30,
        y: 460,
        width: FRAME_SIZES.medium.width - 60,
        height: 40,
        text: 'נועה',
        fontFamily: 'Assistant',
        fontSize: 26,
        fontWeight: 600,
        fill: '#9932cc',
        textAlign: 'center',
        zIndex: 4,
      }),
      createTextElement({
        id: 'age-3',
        name: 'גיל',
        x: 30,
        y: 510,
        width: FRAME_SIZES.medium.width - 60,
        height: 40,
        text: '🎂 5 🎂',
        fontSize: 24,
        textAlign: 'center',
        zIndex: 5,
      }),
    ],
  },

  // ========== BABY ==========
  {
    id: 'baby-welcome',
    name: 'Welcome Baby',
    nameHe: 'ברוך הבא תינוק',
    category: 'baby',
    description: 'תבנית חמודה לברית/הולדת תינוק',
    canvasWidth: FRAME_SIZES.medium.width,
    canvasHeight: FRAME_SIZES.medium.height,
    elements: [
      createShapeElement({
        id: 'bg-4',
        name: 'רקע',
        x: 0,
        y: 0,
        width: FRAME_SIZES.medium.width,
        height: FRAME_SIZES.medium.height,
        fill: '#e0f7fa',
        zIndex: 0,
        isLocked: true,
      }),
      createTextElement({
        id: 'stars-4',
        name: 'כוכבים',
        x: 30,
        y: 20,
        width: FRAME_SIZES.medium.width - 60,
        height: 40,
        text: '⭐ ✨ ⭐ ✨ ⭐',
        fontSize: 18,
        textAlign: 'center',
        zIndex: 1,
      }),
      createImagePlaceholder({
        id: 'photo-4',
        name: 'תמונת תינוק',
        x: 80,
        y: 80,
        width: FRAME_SIZES.medium.width - 160,
        height: FRAME_SIZES.medium.width - 160,
        borderRadius: 150,
        zIndex: 2,
      }),
      createTextElement({
        id: 'welcome-4',
        name: 'ברכה',
        x: 30,
        y: 400,
        width: FRAME_SIZES.medium.width - 60,
        height: 40,
        text: 'ברוך הבא לעולם',
        fontFamily: 'Secular One',
        fontSize: 24,
        fill: '#00acc1',
        textAlign: 'center',
        zIndex: 3,
      }),
      createTextElement({
        id: 'name-4',
        name: 'שם',
        x: 30,
        y: 450,
        width: FRAME_SIZES.medium.width - 60,
        height: 45,
        text: 'אורי',
        fontFamily: 'David Libre',
        fontSize: 36,
        fontWeight: 700,
        fill: '#333333',
        textAlign: 'center',
        zIndex: 4,
      }),
      createTextElement({
        id: 'date-4',
        name: 'תאריך',
        x: 30,
        y: 510,
        width: FRAME_SIZES.medium.width - 60,
        height: 30,
        text: 'נולד: 10.01.2024',
        fontFamily: 'Assistant',
        fontSize: 16,
        fill: '#666666',
        textAlign: 'center',
        zIndex: 5,
      }),
      createTextElement({
        id: 'baby-4',
        name: 'אייקון',
        x: (FRAME_SIZES.medium.width - 50) / 2,
        y: 550,
        width: 50,
        height: 40,
        text: '👶',
        fontSize: 30,
        textAlign: 'center',
        zIndex: 6,
      }),
    ],
  },

  // ========== FAMILY ==========
  {
    id: 'family-reunion',
    name: 'Family Reunion',
    nameHe: 'מפגש משפחתי',
    category: 'family',
    description: 'תבנית למפגשים משפחתיים',
    canvasWidth: FRAME_SIZES.large.width,
    canvasHeight: FRAME_SIZES.large.height,
    elements: [
      createShapeElement({
        id: 'bg-5',
        name: 'רקע',
        x: 0,
        y: 0,
        width: FRAME_SIZES.large.width,
        height: FRAME_SIZES.large.height,
        fill: '#fffbeb',
        zIndex: 0,
        isLocked: true,
      }),
      createTextElement({
        id: 'title-5',
        name: 'כותרת',
        x: 30,
        y: 30,
        width: FRAME_SIZES.large.width - 60,
        height: 50,
        text: 'המשפחה שלנו',
        fontFamily: 'Secular One',
        fontSize: 32,
        fill: '#92400e',
        textAlign: 'center',
        zIndex: 1,
      }),
      createImagePlaceholder({
        id: 'photo-5',
        name: 'תמונת משפחה',
        x: 40,
        y: 100,
        width: FRAME_SIZES.large.width - 80,
        height: 400,
        borderRadius: 10,
        zIndex: 2,
      }),
      createTextElement({
        id: 'event-5',
        name: 'אירוע',
        x: 30,
        y: 520,
        width: FRAME_SIZES.large.width - 60,
        height: 35,
        text: 'מפגש משפחתי שנתי',
        fontFamily: 'Assistant',
        fontSize: 22,
        fill: '#666666',
        textAlign: 'center',
        zIndex: 3,
      }),
      createTextElement({
        id: 'year-5',
        name: 'שנה',
        x: 30,
        y: 565,
        width: FRAME_SIZES.large.width - 60,
        height: 35,
        text: '2024',
        fontFamily: 'Assistant',
        fontSize: 20,
        fontWeight: 600,
        fill: '#92400e',
        textAlign: 'center',
        zIndex: 4,
      }),
      createTextElement({
        id: 'hearts-5',
        name: 'לבבות',
        x: 30,
        y: 620,
        width: FRAME_SIZES.large.width - 60,
        height: 40,
        text: '❤️ 👨‍👩‍👧‍👦 ❤️',
        fontSize: 24,
        textAlign: 'center',
        zIndex: 5,
      }),
    ],
  },

  // ========== EVENT ==========
  {
    id: 'event-party',
    name: 'Party Event',
    nameHe: 'מסיבה',
    category: 'event',
    description: 'תבנית למסיבות ואירועים',
    canvasWidth: FRAME_SIZES.square.width,
    canvasHeight: FRAME_SIZES.square.height,
    elements: [
      createShapeElement({
        id: 'bg-6',
        name: 'רקע',
        x: 0,
        y: 0,
        width: FRAME_SIZES.square.width,
        height: FRAME_SIZES.square.height,
        fill: '#1a1a2e',
        zIndex: 0,
        isLocked: true,
      }),
      createTextElement({
        id: 'confetti-6',
        name: 'קונפטי',
        x: 20,
        y: 10,
        width: FRAME_SIZES.square.width - 40,
        height: 40,
        text: '🎊 ✨ 🎉 ✨ 🎊',
        fontSize: 22,
        textAlign: 'center',
        zIndex: 1,
      }),
      createImagePlaceholder({
        id: 'photo-6',
        name: 'תמונה',
        x: 50,
        y: 70,
        width: FRAME_SIZES.square.width - 100,
        height: 250,
        borderRadius: 10,
        zIndex: 2,
      }),
      createTextElement({
        id: 'title-6',
        name: 'כותרת',
        x: 20,
        y: 340,
        width: FRAME_SIZES.square.width - 40,
        height: 45,
        text: 'המסיבה של',
        fontFamily: 'Assistant',
        fontSize: 20,
        fill: '#ffffff',
        textAlign: 'center',
        zIndex: 3,
      }),
      createTextElement({
        id: 'name-6',
        name: 'שם',
        x: 20,
        y: 385,
        width: FRAME_SIZES.square.width - 40,
        height: 50,
        text: 'דני',
        fontFamily: 'Secular One',
        fontSize: 36,
        fill: '#ffd700',
        textAlign: 'center',
        zIndex: 4,
      }),
      createTextElement({
        id: 'party-6',
        name: 'אייקון',
        x: (FRAME_SIZES.square.width - 60) / 2,
        y: 440,
        width: 60,
        height: 40,
        text: '🎉',
        fontSize: 32,
        textAlign: 'center',
        zIndex: 5,
      }),
    ],
  },

  // ========== BUSINESS ==========
  {
    id: 'business-professional',
    name: 'Professional',
    nameHe: 'מקצועי',
    category: 'business',
    description: 'תבנית מקצועית לעסקים',
    canvasWidth: FRAME_SIZES.medium.width,
    canvasHeight: FRAME_SIZES.medium.height,
    elements: [
      createShapeElement({
        id: 'bg-7',
        name: 'רקע',
        x: 0,
        y: 0,
        width: FRAME_SIZES.medium.width,
        height: FRAME_SIZES.medium.height,
        fill: '#ffffff',
        zIndex: 0,
        isLocked: true,
      }),
      createShapeElement({
        id: 'header-7',
        name: 'כותרת עליונה',
        x: 0,
        y: 0,
        width: FRAME_SIZES.medium.width,
        height: 80,
        fill: '#1e3a5f',
        zIndex: 1,
      }),
      createImagePlaceholder({
        id: 'logo-7',
        name: 'לוגו',
        x: (FRAME_SIZES.medium.width - 60) / 2,
        y: 10,
        width: 60,
        height: 60,
        borderRadius: 30,
        zIndex: 2,
      }),
      createImagePlaceholder({
        id: 'photo-7',
        name: 'תמונה',
        x: 40,
        y: 100,
        width: FRAME_SIZES.medium.width - 80,
        height: 280,
        zIndex: 3,
      }),
      createTextElement({
        id: 'company-7',
        name: 'שם חברה',
        x: 20,
        y: 400,
        width: FRAME_SIZES.medium.width - 40,
        height: 40,
        text: 'שם העסק',
        fontFamily: 'Assistant',
        fontSize: 24,
        fontWeight: 700,
        fill: '#1e3a5f',
        textAlign: 'center',
        zIndex: 4,
      }),
      createTextElement({
        id: 'tagline-7',
        name: 'סלוגן',
        x: 20,
        y: 450,
        width: FRAME_SIZES.medium.width - 40,
        height: 30,
        text: 'הסלוגן שלכם כאן',
        fontFamily: 'Assistant',
        fontSize: 16,
        fill: '#666666',
        textAlign: 'center',
        zIndex: 5,
      }),
      createShapeElement({
        id: 'footer-7',
        name: 'כותרת תחתונה',
        x: 0,
        y: FRAME_SIZES.medium.height - 50,
        width: FRAME_SIZES.medium.width,
        height: 50,
        fill: '#1e3a5f',
        zIndex: 6,
      }),
      createTextElement({
        id: 'contact-7',
        name: 'יצירת קשר',
        x: 20,
        y: FRAME_SIZES.medium.height - 40,
        width: FRAME_SIZES.medium.width - 40,
        height: 30,
        text: '📞 050-1234567 | 📧 info@company.com',
        fontFamily: 'Assistant',
        fontSize: 12,
        fill: '#ffffff',
        textAlign: 'center',
        zIndex: 7,
      }),
    ],
  },
];

// Get templates by category
export const getTemplatesByCategory = (category: TemplateCategory): Template[] => {
  return TEMPLATES.filter(t => t.category === category);
};

// Get all templates
export const getAllTemplates = (): Template[] => {
  return TEMPLATES;
};

// Get template by ID
export const getTemplateById = (id: string): Template | undefined => {
  return TEMPLATES.find(t => t.id === id);
};
